### ISSUE TITLE
win10 小米渠道登录无效

### ISSUE THREAD

**Issue by backlund-zhou** [Alexander-Porter/idv-login#18]
按流程导入了小米账号，执行扫码时提示web端登录成功，游戏端先是进入确认登录的界面，随后跳转回最开始的界面
渠道：小米渠道服
游戏：阴阳师
![image](https://github.com/Alexander-Porter/idv-login/assets/110714802/bc38c056-df40-4136-ba21-ab2833b44bc4)

**Comment by Alexander-Porter** [comment]
### 如果是个人使用，参考以下解决方案（未经实验，动手能力强的可以试试）

1. 下载阴阳师小米渠道服安装包Apk，用jadx (PC) 或者mt管理器（Anddroid）打开。
2. 从androidmanifest.xml文件里找到形如28823037615176xxx的AppId
3. 替换`src/channelHandler/miChannelHandler.py`里Line 52的值为阴阳师的AppID
4. 重新打包或者直接python main.py启动

上面这个流程的通用解决方案暑假会写

**Comment by zhangzhoudezhang** [comment]
修改后提示登录时还是提示写模拟失败
![image](https://github.com/Alexander-Porter/idv-login/assets/110714802/238117a0-1ce2-45f0-ae64-176de216adb8)
![image](https://github.com/Alexander-Porter/idv-login/assets/110714802/2755dbcd-9ec5-468b-a3b7-4e8e73e998b8)
![image](https://github.com/Alexander-Porter/idv-login/assets/110714802/2e52f2f8-c0b1-4eac-9531-5f55aac1247c)

应用界面报错如下：（似乎是某处签名有问题？）
2024-06-09 09:04:28,227 [channelHandler.miChannelHandler] INFO - Get unisdk data for {'code': 401, 'subcode': 0, 'status': 'auth fail', 'debug_message': 'eyJlcnJjb2RlIjo0MDAyLCJhZHVsdCI6MCwiYWdlIjowfQ=='}
2024-06-09 09:04:28,232 [channelmgr] ERROR - 模拟扫码请求失败
Traceback (most recent call last):
  File "channelmgr.py", line 267, in simulate_scan
  File "channelmgr.py", line 225, in simulate_confirm
  File "channelHandler\miChannelHandler.py", line 134, in get_uniSdk_data
KeyError: 'unisdk_login_json'
Stack (most recent call last):
  File "gevent\baseserver.py", line 34, in _handle_and_close_when_done
  File "gevent\server.py", line 210, in wrap_socket_and_handle
  File "gevent\pywsgi.py", line 1700, in handle
  File "gevent\pywsgi.py", line 574, in handle
  File "gevent\pywsgi.py", line 804, in handle_one_request
  File "gevent\pywsgi.py", line 1107, in handle_one_response
  File "gevent\pywsgi.py", line 1053, in run_application
  File "flask\app.py", line 1498, in __call__
  File "flask\app.py", line 1473, in wsgi_app
  File "flask\app.py", line 880, in full_dispatch_request
  File "flask\app.py", line 865, in dispatch_request
  File "proxymgr.py", line 275, in _switch_channel
  File "channelmgr.py", line 272, in simulate_scan
  
![image](https://github.com/Alexander-Porter/idv-login/assets/110714802/79a0a9f6-b248-4497-ab68-31782ca37da7)

**Comment by Alexander-Porter** [comment]
> 修改后提示登录时还是提示写模拟失败 ![image](https://private-user-images.githubusercontent.com/110714802/337939676-238117a0-1ce2-45f0-ae64-176de216adb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDAxMDksIm5iZiI6MTcxNzg5OTgwOSwicGF0aCI6Ii8xMTA3MTQ4MDIvMzM3OTM5Njc2LTIzODExN2EwLTFjZTItNDVmMC1hZTY0LTE3NmRlMjE2YWRiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwMjIzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTU1OTBhMGY1NmUwZWQ3MzllNmMwYmRjNjY5ZWY0M2Q4NjhjYmY0ZTM0ZGNhZGVjZDFkOThhNDhlYmNkNzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RihqLxac5TIGlYPQRIkSs6SWbzsWOoXb0aIg03lIyJM) ![image](https://private-user-images.githubusercontent.com/110714802/337939688-2755dbcd-9ec5-468b-a3b7-4e8e73e998b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDAxMDksIm5iZiI6MTcxNzg5OTgwOSwicGF0aCI6Ii8xMTA3MTQ4MDIvMzM3OTM5Njg4LTI3NTVkYmNkLTllYzUtNDY4Yi1hM2I3LTRlOGU3M2U5OThiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwMjIzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjY2YzYzZDhkMmY4OWM1MGI2ZTgzMDE5ZmQ4MDgwMWZlYjBjYWQxZDc2ZjFjMGEyY2Y3MWQxMzU1YTY4NzBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cj8w0Du1CS3fM9jXwrw7F46EUe1jVkvkOSghfKTzgnk) ![image](https://private-user-images.githubusercontent.com/110714802/337939669-2e52f2f8-c0b1-4eac-9531-5f55aac1247c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDAxMDksIm5iZiI6MTcxNzg5OTgwOSwicGF0aCI6Ii8xMTA3MTQ4MDIvMzM3OTM5NjY5LTJlNTJmMmY4LWMwYjEtNGVhYy05NTMxLTVmNTVhYWMxMjQ3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwMjIzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDMxOWI0YjY2ODJlNTBlNjFlNjViYTVjYTc5NGMyOGUyYjEwZTM5MzJlNTYyMmQ2NWU0NjgwNmEwMWU1NDRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D_XV32a28_UStqlJfOlLD0BpeVc_zgCP8ox7Ul9R5j0)
> 
> 应用界面报错如下：（似乎是某处签名有问题？） 2024-06-09 09:04:28,227 [channelHandler.miChannelHandler] INFO - Get unisdk data for {'code': 401, 'subcode': 0, 'status': 'auth fail', 'debug_message': 'eyJlcnJjb2RlIjo0MDAyLCJhZHVsdCI6MCwiYWdlIjowfQ=='} 2024-06-09 09:04:28,232 [channelmgr] ERROR - 模拟扫码请求失败 Traceback (most recent call last): File "channelmgr.py", line 267, in simulate_scan File "channelmgr.py", line 225, in simulate_confirm File "channelHandler\miChannelHandler.py", line 134, in get_uniSdk_data KeyError: 'unisdk_login_json' Stack (most recent call last): File "gevent\baseserver.py", line 34, in _handle_and_close_when_done File "gevent\server.py", line 210, in wrap_socket_and_handle File "gevent\pywsgi.py", line 1700, in handle File "gevent\pywsgi.py", line 574, in handle File "gevent\pywsgi.py", line 804, in handle_one_request File "gevent\pywsgi.py", line 1107, in handle_one_response File "gevent\pywsgi.py", line 1053, in run_application File "flask\app.py", line 1498, in **call** File "flask\app.py", line 1473, in wsgi_app File "flask\app.py", line 880, in full_dispatch_request File "flask\app.py", line 865, in dispatch_request File "proxymgr.py", line 275, in _switch_channel File "channelmgr.py", line 272, in simulate_scan
> 
> ![image](https://private-user-images.githubusercontent.com/110714802/337939721-79a0a9f6-b248-4497-ab68-31782ca37da7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDAxMDksIm5iZiI6MTcxNzg5OTgwOSwicGF0aCI6Ii8xMTA3MTQ4MDIvMzM3OTM5NzIxLTc5YTBhOWY2LWIyNDgtNDQ5Ny1hYjY4LTMxNzgyY2EzN2RhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwMjIzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGViMzRjNjM1YmIyMTcyYzc1YjRjNzMxNjhhYzcyNDU5YjViOTMwMzMzMDk3MjQ3NGY1ZTY2OWIyMmM4MzBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6lY8Kh7Yo1n_mGcj31e4eP_kkTyEGpjFujj4RYz10Hs)

unisdk data 错误信息经过base64解码如下: 可能和防沉迷有关
`{"errcode":4002,"adult":0,"age":0}`
如果你防沉迷没问题，就是下面的原因
网易游戏每个游戏有个短游戏代号，第五人格是h55，阴阳师应该不一样. 考虑从proxymgr的create_login里把创建扫码登录的请求log一下，修改h55为记录到的game_id
def postSignedData(data):
    url="https://mgbsdk.matrix.netease.com/{game_id}/sdk/uni_sauth"
 def buildSAUTH(login_channel, app_channel,uid,session):
    fakeData = genv.get("FAKE_DEVICE")
    ip=_get_my_ip()
    data = {
        "gameid": game_id,#maybe works for all games

**Comment by zhangzhoudezhang** [comment]
我全局搜了h55相关字段，显示在def get_uniSdk_data还有game_id的相关字段，将上面相关函数的game_id参数修改成阴阳师的g51后登录提示：
2024-06-10 10:20:46,011 [channelHandler.miChannelHandler] INFO - Get unisdk data for {'code': 501, 'subcode': 6, 'status': "header's X-Client-Sign error"}
2024-06-10 10:20:46,016 [channelmgr] ERROR - 模拟扫码请求失败
Traceback (most recent call last):
  File "channelmgr.py", line 272, in simulate_scan
  File "channelmgr.py", line 225, in simulate_confirm
  File "channelHandler\miChannelHandler.py", line 134, in get_uniSdk_data
KeyError: 'unisdk_login_json'
Stack (most recent call last):
  File "gevent\baseserver.py", line 34, in _handle_and_close_when_done
  File "gevent\server.py", line 210, in wrap_socket_and_handle
  File "gevent\pywsgi.py", line 1700, in handle
  File "gevent\pywsgi.py", line 574, in handle
  File "gevent\pywsgi.py", line 804, in handle_one_request
  File "gevent\pywsgi.py", line 1107, in handle_one_response
  File "gevent\pywsgi.py", line 1053, in run_application
  File "flask\app.py", line 1498, in __call__
  File "flask\app.py", line 1473, in wsgi_app
  File "flask\app.py", line 880, in full_dispatch_request
  File "flask\app.py", line 865, in dispatch_request
  File "proxymgr.py", line 276, in _switch_channel
  File "channelmgr.py", line 277, in simulate_scan
  
  我尝试追踪了一下，问题可能是在postSignedData函数，我跟了其中calcSign函数和get_sign_src函数，但是看不出有什么问题

**Comment by Alexander-Porter** [comment]
现在来看，不同游戏的LOG_KEY不一样。可能要继续jadx找字符串常量。第五人格里这个常量的名字叫logKey，建议你把第五人格apk拖进jadx找到字段名再在阴阳师的apk里搜这个字段

**Comment by Alexander-Porter** [comment]
新版已解决
