### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Ghost01900** [Alexander-Porter/idv-login#25]
2024-06-19 16:32:50,612 [__main__] ERROR - 发生未处理的异常:embedded null character.日志路径:C:\ProgramData\idv-login下 的log.txt
Traceback (most recent call last):
  File "main.py", line 106, in <module>
  File "main.py", line 68, in initialize
  File "hostmgr.py", line 42, in __init__
  File "python_hosts\hosts.py", line 161, in __init__
  File "python_hosts\hosts.py", line 495, in populate_entries
  File "python_hosts\hosts.py", line 108, in get_entry_type
  File "python_hosts\utils.py", line 31, in is_ipv6
ValueError: embedded null character
Stack (most recent call last):
  File "main.py", line 142, in <module>
拦截退出事件.
[log.txt](https://github.com/user-attachments/files/15897951/log.txt)

**Comment by Alexander-Porter** [comment]
删掉Hosts文件
